# Generated by Django 2.1.2 on 2019-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20190320_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
