# Generated by Django 2.1.2 on 2019-03-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
