# Generated by Django 2.1.2 on 2019-03-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trailing_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
