# Generated by Django 2.1.2 on 2019-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_post_trailing_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
